#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dumbkan"
name = "DumbKan"
description.en = "Dumb Kanban"
description.fr = "Kanban simple"

version = "2025.03.04~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://www.dumbware.io/"
admindoc = "https://www.dumbware.io/DumbKan"
code = "https://github.com/DumbWareio/DumbKan"
fund = "https://buymeacoffee.com/dumbware"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dumbkan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DumbWareio/DumbKan/archive/5e009d5c2543a8a24cef134487d36d4b390ab943.tar.gz"
    sha256 = "dd29b611b7c3d77237e2fc29ef7473b424cd5ef3690e24f17402f8d203523dc3"
    autoupdate.upstream = "https://github.com/DumbWareio/DumbKan"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
