#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dumbkan"
name = "DumbKan"
description.en = "Dumb Kanban"
description.fr = "Kanban simple"

version = "2025.03.02~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://www.dumbware.io/"
code = "https://github.com/DumbWareio/DumbKan"
fund = "https://buymeacoffee.com/dumbware"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dumbkan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DumbWareio/DumbKan/archive/f6b2b051dce305f6f7fe2703edb4f931f8907cb1.tar.gz"
    sha256 = "4ae2f32209f8e0ee6e2cb79f9d2e4ec3abf1e2f998fa2ca414f8cdb62b35942b"
    autoupdate.upstream = "https://github.com/DumbWareio/DumbKan"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
